language: python
env:
  - TOXENV=py27
allow_failures:
  env:
    - TOXENV=pypy
    - TOXENV=py27-trunkdeps
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
