language: python
env:
  - TOXENV=py27
  - TOXENV=pypy
install:
  - pip install tox
  - pip install twisted
  - pip install epsilon
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
